using System.Collections.Generic;
using UnityEngine;

namespace AuraKnight.Audio
{
    /// <summary>ScriptableObject lookup from <see cref="SfxId"/> to its clips. Generated by AudioAssetGenerator.</summary>
    [CreateAssetMenu(menuName = "Aura Knight/Audio/Sfx Library", fileName = "SfxLibrary")]
    public sealed class SfxLibrary : ScriptableObject
    {
        [SerializeField] SfxEntry[] entries = System.Array.Empty<SfxEntry>();

        Dictionary<SfxId, SfxEntry> _byId;

        public IReadOnlyList<SfxEntry> Entries => entries;

        /// <summary>Replaces the rows (generators and tests). Duplicate ids: the first row wins.</summary>
        public void SetEntries(SfxEntry[] rows)
        {
            entries = rows ?? System.Array.Empty<SfxEntry>();
            _byId = null;
        }

        public bool TryGet(SfxId id, out SfxEntry entry)
        {
            if (_byId == null) Index();
            return _byId.TryGetValue(id, out entry);
        }

        void OnValidate() => _byId = null;

        void Index()
        {
            _byId = new Dictionary<SfxId, SfxEntry>(entries.Length);
            foreach (var e in entries)
                if (e != null && e.id != SfxId.None && !_byId.ContainsKey(e.id)) _byId.Add(e.id, e);
        }
    }
}
