using System.Linq;
using NUnit.Framework;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace AuraKnight.Tests.Integration
{
    /// <summary>The Core scene file itself carries the one AudioListener (on the main camera), generated by the world scene generator.</summary>
    public sealed class CoreSceneAudioTests
    {
        const string CorePath = "Assets/_Project/Scenes/Core.unity";

        [Test]
        public void TheCoreMainCameraHasTheOnlyAudioListener()
        {
            var scene = EditorSceneManager.OpenScene(CorePath, OpenSceneMode.Additive);
            try
            {
                var listeners = scene.GetRootGameObjects().SelectMany(go => go.GetComponentsInChildren<AudioListener>(true)).ToArray();
                Assert.AreEqual(1, listeners.Length, "exactly one listener in Core");
                var camera = listeners[0].GetComponent<Camera>();
                Assert.IsNotNull(camera, "the listener sits on a camera");
                Assert.AreEqual("MainCamera", camera.tag);
            }
            finally { EditorSceneManager.CloseScene(scene, true); }
        }
    }
}
